// TurboQuant 4-bit Flash Attention vec kernel instantiations
// Only D=128 needed (QK_TURBO4 = 128 = head_dim)

#include "fattn-vec.cuh"

// K=TURBO4_0 combinations
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBO4_0, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBO4_0, GGML_TYPE_TURBO4_0);

// V=TURBO4_0 with common K types
DECL_FATTN_VEC_CASE(128, GGML_TYPE_F16,  GGML_TYPE_TURBO4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q4_0, GGML_TYPE_TURBO4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q8_0, GGML_TYPE_TURBO4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_BF16, GGML_TYPE_TURBO4_0);
